-   repo: local
    hooks:
    -   id: autopep8
        name: autopep8
        entry: autopep8 -i
        language: python
        files: ^rl/
        types: [python]
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        files: ^rl/
        types: [python]
